volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kalmmar4uk/dashboard_backend
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    image: breadkvass/dashboard_frontend
    ports: 
     - 80:8080
  nginx:
    image: kalmmar4uk/dashboard_nginx
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/