# Generated by Django 4.2 on 2024-10-17 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField(verbose_name='Дата оценки')),
                ('type_evaluation', models.CharField(max_length=30, verbose_name='Тип оценки')),
                ('value_evaluation', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Значение оценки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий оценки')),
                ('accordance', models.BooleanField(null=True, verbose_name='Соответствие')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Навык сотрудника',
                'verbose_name_plural': 'Навыки сотрудников',
            },
        ),
        migrations.CreateModel(
            name='IndividualDevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=50, verbose_name='Цель')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'План развития',
                'verbose_name_plural': 'Планы развития',
            },
        ),
        migrations.CreateModel(
            name='MinScoreByGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=6, verbose_name='Грейд')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('competence', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('min_score', models.PositiveSmallIntegerField(verbose_name='Значение оценки')),
            ],
            options={
                'verbose_name': 'Минимальная оценка навыка',
                'verbose_name_plural': 'Минимальная оценка навыков',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('domen', models.CharField(max_length=15, verbose_name='Тип навыка')),
                ('skill_score', models.FloatField(default=1, verbose_name='Минимальная оценка навыка')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
