# Generated by Django 4.2 on 2024-10-06 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualdevelopmentplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.skills', verbose_name='Навык'),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
