# Generated by Django 4.2 on 2024-10-06 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenceuser',
            name='date_passage',
            field=models.DateField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
        migrations.CreateModel(
            name='CompetencyAssessmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.competencyassessment', verbose_name='Оценка компетенции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
