# Generated by Django 4.2 on 2024-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_alter_competenceuser_date_passage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='hard_skill',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='soft_skill',
        ),
        migrations.AddField(
            model_name='competence',
            name='domen',
            field=models.CharField(default=1, max_length=15, verbose_name='Домен'),
            preserve_default=False,
        ),
    ]
