# Generated by Django 4.2 on 2024-10-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_remove_user_date_accession_and_more'),
        ('competencies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskills',
            name='appreciated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appreciateds', to='users.employee', verbose_name='Оценивший'),
        ),
        migrations.AlterField(
            model_name='employeeskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_employeeskills', to='users.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee', verbose_name='Сотрудник'),
        ),
    ]
