# Generated by Django 4.2 on 2024-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0004_alter_evaluation_appreciated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeskills',
            options={'verbose_name': 'Навык сотрудника', 'verbose_name_plural': 'Навыки сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='individualdevelopmentplan',
            options={'verbose_name': 'План развития', 'verbose_name_plural': 'Планы развития'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualdevelopmentplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
