# Generated by Django 4.2 on 2024-10-11 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competencies', '0009_evaluation_type_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeskills',
            name='competence_score',
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='accordance',
            field=models.BooleanField(null=True, verbose_name='Соответствие'),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='appreciated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appreciateds', to=settings.AUTH_USER_MODEL, verbose_name='Оценивший'),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий оценки'),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='date_evaluation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата оценки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='type_evaluation',
            field=models.CharField(default=1, max_length=30, verbose_name='Тип оценки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='value_evaluation',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Значение оценки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
