# Generated by Django 4.2 on 2024-10-13 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competencies', '0010_remove_employeeskills_competence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskills',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence', to='competencies.skills', verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='employeeskills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_employeeskills', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
