# Generated by Django 4.2 on 2024-10-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0011_alter_employeeskills_competence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinScoreByGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=6, verbose_name='Грейд')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('competence', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('min_score', models.PositiveSmallIntegerField(verbose_name='Значение оценки')),
            ],
            options={
                'verbose_name': 'Минимальная оценка навыка',
                'verbose_name_plural': 'Минимальная оценка навыков',
            },
        ),
        migrations.AlterField(
            model_name='individualdevelopmentplan',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
