# Generated by Django 4.2 on 2024-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.BooleanField(default=True, help_text='Отметить, если является сотрудником', verbose_name='Сотрудник'),
        ),
    ]
