# Generated by Django 4.2 on 2024-10-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_options_alter_team_options_and_more'),
        ('users', '0004_alter_team_options_team_is_deleted_user_is_deleted'),
    ]

    operations = [
    ]
