# Generated by Django 4.2 on 2024-10-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employee_team_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='count_user',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
