# Generated by Django 4.2 on 2024-10-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_team_count_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='count_user',
        ),
    ]
