# Generated by Django 4.2 on 2024-10-13 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_team_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Команда'),
        ),
    ]
