# Generated by Django 4.2 on 2024-10-14 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_team_team_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название команды'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
